export const starterSources = [
  {
    provider: "OpenAI",
    name: "OpenAI API Changelog",
    url: "https://platform.openai.com/docs/changelog",
    type: "changelog",
    category: "api",
    priority: "high",
    active: true,
    notes: "Official OpenAI API changelog.",
  },
  {
    provider: "Anthropic",
    name: "Claude Release Notes",
    url: "https://docs.anthropic.com/en/release-notes/overview",
    type: "release_notes",
    category: "platform",
    priority: "high",
    active: true,
    notes: "Official Claude platform release notes.",
  },
  {
    provider: "Google",
    name: "Gemini API Release Notes",
    url: "https://ai.google.dev/gemini-api/docs/changelog",
    type: "release_notes",
    category: "api",
    priority: "high",
    active: true,
    notes: "Official Gemini API release notes.",
  },
  {
    provider: "Microsoft",
    name: "Microsoft Foundry What's New",
    url: "https://learn.microsoft.com/en-us/azure/foundry/whats-new-foundry",
    type: "docs_page",
    category: "enterprise_ai",
    priority: "medium",
    active: true,
    notes: "Microsoft AI platform update source.",
  },
] as const
